### PR TITLE
Added support for removing directories as well as files.

### PR DESCRIPTION
**Pull request by kubischj**
Now the script removes directories as well as files. More danger, more fun!

### CODE REVIEW

**Review by Mimaaa — APPROVED** [review]
Love it! :see_no_evil:

**Comment by Mimaaa** [comment]
@kubischj I just published the new version to npm. Never expected a PR and never really finished the package to the point that it works.

**Comment by kubischj** [comment]
Nice, thanks 👍

**Comment by Mimaaa** [comment]
It still doesn't work though. Atleast, for me. :confused: I'll fix it later.

**Pull request merged**
